name: Python autotest full steps

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: "Choose test set"
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - extended
          - all

permissions:
  contents: read
  actions: write
  id-token: write

jobs:
  download-history:
    runs-on: ubuntu-latest
    name: Download history
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Download artifacts
        run: |
          download_artifact() {
            local artifact_name=$1
            local output_dir=$2
            local artifact_id=$(curl -sL \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?name=$artifact_name" \
              | jq -r '.artifacts[0].id')
            
            if [ -n "$artifact_id" ]; then
              curl -L \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id/zip" \
                -o "$output_dir.zip"
              mkdir -p "$output_dir"
              unzip -q "$output_dir.zip" -d "$output_dir"
            fi
          }

          sudo apt-get update && sudo apt-get install -y jq
          download_artifact "allure-results" "allure-history"
          download_artifact "github-pages" "old_pages"

      - name: Extract pages history
        run: |
          mkdir -p allure-history
          tar -xf old_pages/artifact.tar -C pages_history || true
          cp -r pages_history/history/* allure-history/ || true

      - name: Store allure history
        uses: actions/upload-artifact@v4
        with:
          name: allure-history-${{ github.run_id }}-${{ github.run_attempt }}
          path: allure-history
          retention-days: 1
          overwrite: true

  test:
    runs-on: ubuntu-latest
    needs: download-history
    name: Run tests
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y wget google-chrome-stable
          pip install -r requirements.txt pytest-xdist pytest-rerunfailures allure-pytest

      - name: Download history artifacts
        uses: actions/download-artifact@v4
        with:
          name: allure-history-${{ github.run_id }}-${{ github.run_attempt }}
          path: allure-results/history

      - name: Run tests
        run: |
          pytest -vs -n 3 --reruns 2 --alluredir=allure-results \
            --strict-markers \
            -p no:unknown-mark \
            -m "${{ github.event.inputs.deployment_target }}"
        continue-on-error: true

      - name: Upload allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ github.run_id }}-${{ github.run_attempt }}
          path: allure-results
          retention-days: 1
          overwrite: true

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate report
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Install Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz
          sudo tar -zxvf allure-2.23.1.tgz -C /opt/
          sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure

      - name: Download allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-${{ github.run_id }}-${{ github.run_attempt }}
          path: allure-results

      - name: Generate Allure report
        run: |
          allure generate -c allure-results -o _site

      - name: Store generated report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ github.run_id }}-${{ github.run_attempt }}
          path: _site
          retention-days: 1
          overwrite: true

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Report publication
    steps:
      - name: Download generated report
        uses: actions/download-artifact@v4
        with:
          name: allure-report-${{ github.run_id }}-${{ github.run_attempt }}
          path: _site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
