name: Python autotest

on: 
  workflow_dispatch:
    inputs:
      deplowment_target:
        description: choose test set
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regretion
          - extended
          - all
      

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotest
    steps:
      - name: Checkout autotest
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Run all test  
        if: "github.event.inputs.deplowment_target == 'all'"
        run: pytest
      - name: Run smoke test  
        if: "github.event.inputs.deplowment_target == 'smoke'"
        run: pytest
      - name: Run regression test  
        if: "github.event.inputs.deplowment_target == 'regression'"
        run: pytest
      - name: Run extended test  
        if: "github.event.inputs.deplowment_target == 'extended'"
        run: pytest
