name: Python autotest

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotest
    steps:
      - name: Checkout autotest
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run test  
        env:
          # Указываем путь к Chrome и ChromeDriver
          CHROME_PATH: /usr/bin/chromium-browser
          CHROME_DRIVER_PATH: /usr/bin/chromedriver
        run: pytest
